### ISSUE TITLE
Documentation about VPN/Network access message instead of `No internet connection()`

### ISSUE THREAD

**Issue by Lextuga007** [kvasilopoulos/onsr#6]
The following function:

```
onsr::ons_datasets()
```

Just returns the error `No internet connection.` as I'm on a public sector (NHS) computer. I get the data when I'm logged into a VPN and I just wondered if it would be possible to add to the message something about requiring a secure network to access the data?

Thanks for a great package - this is something I want to promote more through the [NHS-R Community](https://nhsrcommunity.com/) as it's easier to use packages like this that dive into APIs 😃

**Comment by kvasilopoulos** [comment]
Hi, thanks for the feedback. So the issues is that:

**With VPN:**
You can call the package with no issues.

**Without VPN:**
You cannot call the package and you get the` No internet connection`. So you want to **ONLY** modify the user message in order for the people to understand that they need to enable the VPN in order to use the package.

If this is the case then I think something like 

```Unable to connect: Please ensure you have an active internet connection or access through a secure connection.``` 

is more appropriate. What do you think?

**Comment by Lextuga007** [comment]
That looks perfect as a message - thanks.
